[package]
name = "simple_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4"
hostname = "^0.3"
gethostname = "^0.4.3"
whoami = "^0.9"
libc = "^0.2"